// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1
{
    public partial class ActiveRatingScheme
    {
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public bool Error { get; set; }
        public long RatingSchemeRecordId { get; set; }
        public long RecordId { get; set; }
        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual RatingScheme RatingSchemeRecord { get; set; }
    }
}