// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1
{
    public partial class CountryGroupRatingCurrency
    {
        public CountryGroupRatingCurrency()
        {
            CountryGroupToEquityFactor = new HashSet<CountryGroupToEquityFactor>();
        }

        public long CountryGroupRatingOrderRecordId { get; set; }
        public long CurrencyRecordId { get; set; }
        public long RecordId { get; set; }

        public virtual CountryGroupRatingOrder CountryGroupRatingOrderRecord { get; set; }
        public virtual Currency CurrencyRecord { get; set; }
        public virtual ICollection<CountryGroupToEquityFactor> CountryGroupToEquityFactor { get; set; }
    }
}