// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1
{
    public partial class CountryGroup
    {
        public CountryGroup()
        {
            CountryGroupRatingOrder = new HashSet<CountryGroupRatingOrder>();
        }

        public string CountryGroupId { get; set; }
        public long? LabelRecordId { get; set; }
        public long? DescriptionLabelRecordId { get; set; }
        public long RecordId { get; set; }
        public long? OwnerPartyRecordId { get; set; }
        public long? OwnerBaseCompanyRecordId { get; set; }
        public long? PurposeRecordId { get; set; }
        public bool Default { get; set; }
        public bool? Active { get; set; }
        public long UpdatedBy { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime ChangeDate { get; set; }

        public virtual ICollection<CountryGroupRatingOrder> CountryGroupRatingOrder { get; set; }
    }
}