// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1
{
    public partial class CountryGroupRatingOrder
    {
        public long RatingSchemeRecordId { get; set; }
        public long CountryGroupRecordId { get; set; }
        public int SortValue { get; set; }
        public long RecordId { get; set; }

        public virtual CountryGroup CountryGroupRecord { get; set; }
        public virtual RatingScheme RatingSchemeRecord { get; set; }
        public virtual CountryGroupRatingCurrency CountryGroupRatingCurrency { get; set; }
    }
}