// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1
{
    public partial class CountryGroupToEquityFactor
    {
        public long RatingSchemeRecordId { get; set; }
        public long CountryGroupRatingCurrencyRecordId { get; set; }
        public long EquityFactorRecordId { get; set; }
        public decimal FromAmountInclusive { get; set; }
        public long RecordId { get; set; }

        public virtual CountryGroupRatingCurrency CountryGroupRatingCurrencyRecord { get; set; }
        public virtual EquityFactor EquityFactorRecord { get; set; }
        public virtual RatingScheme RatingSchemeRecord { get; set; }
    }
}