// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1
{
    public partial class Currency
    {
        public Currency()
        {
            CountryGroupRatingCurrency = new HashSet<CountryGroupRatingCurrency>();
            RatingScheme = new HashSet<RatingScheme>();
        }

        public string CurrencyId { get; set; }
        public int? NumericId { get; set; }
        public bool AcceptedInternalUse { get; set; }
        public bool AcceptedExternalUse { get; set; }
        public string AcceptedInternalNote { get; set; }
        public DateTime? AcceptedInternalNoteDate { get; set; }
        public long? LabelRecordId { get; set; }
        public DateTime? ExpiredDate { get; set; }
        public long RecordId { get; set; }
        public bool? Active { get; set; }
        public long UpdatedBy { get; set; }
        public DateTime ChangeDate { get; set; }

        public virtual ICollection<CountryGroupRatingCurrency> CountryGroupRatingCurrency { get; set; }
        public virtual ICollection<RatingScheme> RatingScheme { get; set; }
    }
}