// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1
{
    public partial class EquityFactor
    {
        public EquityFactor()
        {
            CountryGroupToEquityFactor = new HashSet<CountryGroupToEquityFactor>();
        }

        public string EquityFactorId { get; set; }
        public bool? Active { get; set; }
        public int Flags { get; set; }
        public int Rank { get; set; }
        public long RecordId { get; set; }
        public long UpdatedBy { get; set; }
        public DateTime ChangeDate { get; set; }

        public virtual ICollection<CountryGroupToEquityFactor> CountryGroupToEquityFactor { get; set; }
    }
}