// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ConsoleApp1
{
    public partial class RatingScheme
    {
        public RatingScheme()
        {
            ActiveRatingScheme = new HashSet<ActiveRatingScheme>();
            CountryGroupRatingOrder = new HashSet<CountryGroupRatingOrder>();
            CountryGroupToEquityFactor = new HashSet<CountryGroupToEquityFactor>();
        }

        public string Name { get; set; }
        public int Version { get; set; }
        public string Description { get; set; }
        public long CurrencyRecordId { get; set; }
        public long CurrencyGroupRecordId { get; set; }
        public int AccountExpirationDate { get; set; }
        public long? EquityFactorFormularRecordId { get; set; }
        public byte[] CompiledFormulars { get; set; }
        public bool Dirty { get; set; }
        public long RecordId { get; set; }
        public long UpdatedBy { get; set; }
        public DateTime ChangeDate { get; set; }
        public long CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual Currency CurrencyRecord { get; set; }
        public virtual ICollection<ActiveRatingScheme> ActiveRatingScheme { get; set; }
        public virtual ICollection<CountryGroupRatingOrder> CountryGroupRatingOrder { get; set; }
        public virtual ICollection<CountryGroupToEquityFactor> CountryGroupToEquityFactor { get; set; }
    }
}